#!/usr/bin/env python3
"""
ibvs_cube_node.py

Image-Based Visual Servoing (IBVS) of a red cube using ViSP for the visual
control law and PyKDL (from the live robot_description) for the robot
Jacobian, so that the camera-frame velocity screw computed by ViSP is
mapped to joint velocities correctly -- not via hand-tuned scale factors.

Strategy (as requested)
------------------------
STATE 1 -- Centering (J1-J5 active, J6 locked)
    IBVS on 4 image corners drives the camera-frame velocity v_c via
    ViSP's vpServo. v_c is expressed in the base frame using the current
    camera orientation (from FK) and mapped to qdot_1..5 with the
    pseudo-inverse of the first 5 columns of the base-frame Jacobian.
    J4/J5 naturally participate in this solve (they're part of the
    Jacobian), so they contribute to centering/orientation just like
    J1-J3 -- there's no need to hand-split "which joint does what": the
    pseudo-inverse finds the least-squares combination automatically.

STATE 2 -- Orthogonal alignment while staying centered (task priority)
    Once the cube is centered (image error below a threshold), J4/J5 are
    driven in joint space toward a target orientation (parameters
    target_j4 / target_j5) meant to make the camera axis perpendicular to
    the cube's top face. This joint motion would, by itself, move the
    cube in the image (through the J4/J5 columns of the Jacobian). J1-J3
    are commanded, via the pseudo-inverse of their own Jacobian columns,
    to inject the equal-and-opposite camera motion (feedforward
    decoupling) *plus* the residual IBVS feedback v_c, so the cube stays
    centered while J4/J5 finish their rotation. J6 stays locked.

IMPORTANT -- things you must verify/adjust for your setup
-----------------------------------------------------------
- base_link_frame / camera_frame: must match your URDF's link names
  exactly. Check with:
      ros2 run tf2_tools view_frames
  or grep the URDF: `ros2 topic echo /robot_description --once | grep camera`
- This assumes the camera is rigidly (fixed-joint) mounted after joint_6,
  so the KDL chain base_link -> camera_frame contains exactly the 6
  movable joints in joint_names, in that order. If your URDF differs
  (e.g. gripper joints in between), the column slicing below (J[:, :5],
  J[:, :3], J[:, 3:5]) needs to be adjusted to the correct indices.
- ViSP python binding method/class names were cross-checked against the
  official visp-python-daily autogenerated docs for 3.7.x. If you hit an
  AttributeError, run `python3 -c "import visp.vs as vs; help(vs.Servo)"`
  to check the exact signature in your build.
- joint_vel_limit / max cartesian corrective velocities are conservative
  placeholders -- tune to your robot/sim.
"""

import math
import numpy as np
import cv2

import rclpy
from rclpy.node import Node
from rclpy.action import ActionClient
from rclpy.qos import QoSProfile, ReliabilityPolicy, HistoryPolicy, DurabilityPolicy

from sensor_msgs.msg import Image, JointState
from std_msgs.msg import String
from trajectory_msgs.msg import JointTrajectory, JointTrajectoryPoint
from control_msgs.action import FollowJointTrajectory
from cv_bridge import CvBridge

import PyKDL as kdl
from urdf_parser_py.urdf import URDF as UrdfModel

from visp.core import CameraParameters
from visp.visual_features import FeaturePoint
from visp.vs import Servo


def kdl_jacobian_to_np(jac: kdl.Jacobian) -> np.ndarray:
    m = np.zeros((jac.rows(), jac.columns()))
    for i in range(jac.rows()):
        for j in range(jac.columns()):
            m[i, j] = jac[i, j]
    return m


def kdl_rotation_to_np(R: kdl.Rotation) -> np.ndarray:
    return np.array([[R[0, 0], R[0, 1], R[0, 2]],
                      [R[1, 0], R[1, 1], R[1, 2]],
                      [R[2, 0], R[2, 1], R[2, 2]]])


# ---------------------------------------------------------------------
# Minimal, self-contained URDF -> PyKDL chain builder.
#
# This replaces the `kdl_parser_py` package (not available on this
# system -- only `urdf_parser_py` + `PyKDL` are required, both of which
# are already present since PyKDL imported successfully). It mirrors the
# standard ROS kdl_parser conversion, but only builds a single chain
# (base_link -> tip_link) rather than a full tree, using URDF's own
# get_chain() to find the joint path.
# ---------------------------------------------------------------------
def _make_fixed_kdl_joint(name: str) -> kdl.Joint:
    """Construct a KDL 'no motion' joint. PyKDL bindings have historically been
    inconsistent about how the Fixed joint type is exposed across distros, so
    try the known conventions in order."""
    try:
        return kdl.Joint(name)  # no-arg (besides name) defaults to Fixed in most builds
    except TypeError:
        pass
    for attr in ('Fixed', 'None'):
        try:
            jtype = getattr(kdl.Joint, attr)
            return kdl.Joint(name, jtype)
        except (AttributeError, TypeError):
            continue
    raise RuntimeError('Could not construct a fixed PyKDL.Joint with this PyKDL build.')


def _origin_to_kdl_frame(origin) -> kdl.Frame:
    rpy = list(origin.rpy) if (origin is not None and origin.rpy) else [0.0, 0.0, 0.0]
    xyz = list(origin.xyz) if (origin is not None and origin.xyz) else [0.0, 0.0, 0.0]
    return kdl.Frame(kdl.Rotation.RPY(*rpy), kdl.Vector(*xyz))


def build_kdl_chain_from_urdf(urdf_xml: str, base_link: str, tip_link: str) -> kdl.Chain:
    robot = UrdfModel.from_xml_string(urdf_xml)

    # Ordered list of joint names from base_link to tip_link.
    joint_names = robot.get_chain(base_link, tip_link, links=False, joints=True)

    chain = kdl.Chain()
    for jname in joint_names:
        joint = robot.joint_map[jname]
        F = _origin_to_kdl_frame(joint.origin)

        if joint.type in ('revolute', 'continuous'):
            axis = joint.axis if joint.axis else [1.0, 0.0, 0.0]
            axis_vec = F.M * kdl.Vector(*axis)  # axis expressed in parent link frame
            kdl_joint = kdl.Joint(joint.name, F.p, axis_vec, kdl.Joint.RotAxis)
        elif joint.type == 'prismatic':
            axis = joint.axis if joint.axis else [1.0, 0.0, 0.0]
            axis_vec = F.M * kdl.Vector(*axis)
            kdl_joint = kdl.Joint(joint.name, F.p, axis_vec, kdl.Joint.TransAxis)
        else:  # 'fixed' or unsupported types -> treated as fixed
            kdl_joint = _make_fixed_kdl_joint(joint.name)

        segment = kdl.Segment(joint.child, kdl_joint, F)
        chain.addSegment(segment)

    return chain


class IBVSCubeNode(Node):

    def __init__(self):
        super().__init__('ibvs_cube_node')

        # ---------------- Parameters ----------------
        self.declare_parameter('base_link_frame', 'base_link')
        self.declare_parameter('camera_frame', 'camera_link')  # VERIFY against your URDF
        self.declare_parameter('joint_names',
                                ['joint_1', 'joint_2', 'joint_3', 'joint_4', 'joint_5', 'joint_6'])
        self.declare_parameter('lambda_gain', 0.25)
        self.declare_parameter('centering_error_threshold', 15.0)  # px, task-space feature error norm proxy
        self.declare_parameter('joint_vel_limit', 0.25)  # rad/s, per joint
        self.declare_parameter('target_j4', 0.0)
        self.declare_parameter('target_j5', -1.57)
        self.declare_parameter('phase2_gain', 0.6)

        self.base_link_frame = self.get_parameter('base_link_frame').value
        self.camera_frame = self.get_parameter('camera_frame').value
        self.joint_names = list(self.get_parameter('joint_names').value)
        self.lambda_gain = float(self.get_parameter('lambda_gain').value)
        self.centering_error_threshold = float(self.get_parameter('centering_error_threshold').value)
        self.joint_vel_limit = float(self.get_parameter('joint_vel_limit').value)
        self.target_j4 = float(self.get_parameter('target_j4').value)
        self.target_j5 = float(self.get_parameter('target_j5').value)
        self.phase2_gain = float(self.get_parameter('phase2_gain').value)

        self.n_joints = len(self.joint_names)

        # ---------------- ROS I/O ----------------
        qos_img = QoSProfile(reliability=ReliabilityPolicy.BEST_EFFORT,
                              history=HistoryPolicy.KEEP_LAST, depth=1)
        self.create_subscription(Image, '/wrist_mounted_camera/image/image_raw',
                                  self.image_cb, qos_img)
        self.create_subscription(JointState, '/joint_states', self.joint_state_cb, 10)

        qos_urdf = QoSProfile(reliability=ReliabilityPolicy.RELIABLE,
                               durability=DurabilityPolicy.TRANSIENT_LOCAL,
                               history=HistoryPolicy.KEEP_LAST, depth=1)
        self.create_subscription(String, '/robot_description', self.urdf_cb, qos_urdf)

        self.traj_pub = self.create_publisher(JointTrajectory,
                                               '/joint_trajectory_controller/joint_trajectory', 10)
        self.traj_client = ActionClient(self, FollowJointTrajectory,
                                         '/joint_trajectory_controller/follow_joint_trajectory')

        self.bridge = CvBridge()

        # ---------------- Kinematics (filled once URDF arrives) ----------------
        self.kdl_chain = None
        self.jac_solver = None
        self.fk_solver = None

        # ---------------- ViSP camera + IBVS task ----------------
        self.cam = CameraParameters(554.25469, 554.25469, 320.5, 240.5)  

        self.task = Servo()
        self.task.setServo(Servo.EYEINHAND_CAMERA)
        self.task.setInteractionMatrixType(Servo.CURRENT, Servo.PSEUDO_INVERSE)
        self.task.setLambda(self.lambda_gain)

        self.s = [FeaturePoint() for _ in range(4)]
        self.s_star = [FeaturePoint() for _ in range(4)]

        u_star = [100.0, 540.0, 540.0, 100.0]
        v_star = [80.0, 80.0, 400.0, 400.0]
        self.Z_d = 0.15
        for i in range(4):
            x_star = (u_star[i] - self.cam.get_u0()) / self.cam.get_px()
            y_star = (v_star[i] - self.cam.get_v0()) / self.cam.get_py()
            self.s_star[i].buildFrom(x_star, y_star, self.Z_d)
            self.task.addFeature(self.s[i], self.s_star[i])

        # ---------------- State ----------------
        self.current_q = [0.0] * self.n_joints
        self.has_joint_states = False
        self.state = 0  # 0: move to seed pose, 1: centering, 2: orthogonal alignment
        self.goal_sent = False
        self.last_stamp = None

        self.get_logger().info('IBVS node started. Waiting for /robot_description and joint states...')

    # ------------------------------------------------------------------
    def urdf_cb(self, msg: String):
        if self.kdl_chain is not None:
            return
        try:
            self.kdl_chain = build_kdl_chain_from_urdf(
                msg.data, self.base_link_frame, self.camera_frame)
        except KeyError as e:
            self.get_logger().error(
                f'Could not build KDL chain {self.base_link_frame} -> '
                f'{self.camera_frame}: missing joint/link {e}. Check '
                f'base_link_frame/camera_frame parameters against the URDF.')
            return
        except Exception as e:
            self.get_logger().error(f'Failed to build KDL chain: {e}')
            return
        n = self.kdl_chain.getNrOfJoints()
        if n != self.n_joints:
            self.get_logger().warn(
                f'KDL chain has {n} movable joints but joint_names has {self.n_joints}. '
                f'Check base_link_frame/camera_frame and that the camera is rigidly '
                f'mounted directly after the last arm joint.')
        self.jac_solver = kdl.ChainJntToJacSolver(self.kdl_chain)
        self.fk_solver = kdl.ChainFkSolverPos_recursive(self.kdl_chain)
        self.get_logger().info(f'KDL chain ready: {self.base_link_frame} -> '
                                f'{self.camera_frame} ({n} joints)')

    # ------------------------------------------------------------------
    def joint_state_cb(self, msg: JointState):
        for i, name in enumerate(self.joint_names):
            if name in msg.name:
                self.current_q[i] = msg.position[msg.name.index(name)]
        self.has_joint_states = True

    # ------------------------------------------------------------------
    def send_initial_trajectory(self):
        if self.goal_sent:
            return
        if not self.traj_client.wait_for_server(timeout_sec=2.0):
            self.get_logger().warn('Waiting for joint_trajectory_controller action server...')
            return
        goal_msg = FollowJointTrajectory.Goal()
        goal_msg.trajectory.joint_names = self.joint_names
        point = JointTrajectoryPoint()
        point.positions = [0.0, 0.0, -1.57, 0.0, -1.57, 0.0]
        point.time_from_start.sec = 10
        goal_msg.trajectory.points = [point]
        self.goal_sent = True
        fut = self.traj_client.send_goal_async(goal_msg)
        fut.add_done_callback(self._goal_response_cb)

    def _goal_response_cb(self, future):
        handle = future.result()
        if not handle.accepted:
            self.get_logger().error('Initial trajectory rejected.')
            return
        handle.get_result_async().add_done_callback(self._traj_done_cb)

    def _traj_done_cb(self, future):
        self.get_logger().info('Seed pose reached -- starting IBVS (state 1: centering).')
        self.state = 1

    # ------------------------------------------------------------------
    def detect_red_cube_corners(self, cv_image):
        hsv = cv2.cvtColor(cv_image, cv2.COLOR_BGR2HSV)
        lower_red1, upper_red1 = np.array([0, 70, 50]), np.array([10, 255, 255])
        lower_red2, upper_red2 = np.array([170, 70, 50]), np.array([180, 255, 255])
        mask = cv2.inRange(hsv, lower_red1, upper_red1) | cv2.inRange(hsv, lower_red2, upper_red2)
        contours, _ = cv2.findContours(mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
        for cnt in contours:
            if cv2.contourArea(cnt) > 150:
                peri = cv2.arcLength(cnt, True)
                approx = cv2.approxPolyDP(cnt, 0.04 * peri, True)
                if len(approx) == 4:
                    pts = approx.reshape(4, 2).astype(np.float32)
                    rect = np.zeros((4, 2), dtype='float32')
                    s = pts.sum(axis=1)
                    rect[0] = pts[np.argmin(s)]
                    rect[2] = pts[np.argmax(s)]
                    diff = np.diff(pts, axis=1)
                    rect[1] = pts[np.argmin(diff)]
                    rect[3] = pts[np.argmax(diff)]
                    return rect
        return None

    # ------------------------------------------------------------------
    def _jacobian_and_camera_rotation(self):
        """Returns (J_base [6xN] numpy, R_base_cam [3x3] numpy) at current_q."""
        q_kdl = kdl.JntArray(self.n_joints)
        for i in range(self.n_joints):
            q_kdl[i] = self.current_q[i]

        jac_kdl = kdl.Jacobian(self.n_joints)
        self.jac_solver.JntToJac(q_kdl, jac_kdl)
        J = kdl_jacobian_to_np(jac_kdl)  # 6xN, base frame, ref point = camera origin

        frame = kdl.Frame()
        self.fk_solver.JntToCart(q_kdl, frame)
        R = kdl_rotation_to_np(frame.M)  # camera axes expressed in base frame
        return J, R

    # ------------------------------------------------------------------
    def _solve_qdot(self, J_cols: np.ndarray, v_base: np.ndarray) -> np.ndarray:
        qdot, *_ = np.linalg.lstsq(J_cols, v_base, rcond=None)
        return np.clip(qdot, -self.joint_vel_limit, self.joint_vel_limit)

    # ------------------------------------------------------------------
    def image_cb(self, msg: Image):
        if self.state == 0:
            self.send_initial_trajectory()
            return

        if not self.has_joint_states or self.kdl_chain is None:
            return

        cv_image = self.bridge.imgmsg_to_cv2(msg, 'bgr8')
        stamp = msg.header.stamp.sec + msg.header.stamp.nanosec * 1e-9
        dt = 0.05 if self.last_stamp is None else max(1e-3, min(0.2, stamp - self.last_stamp))
        self.last_stamp = stamp

        detected = self.detect_red_cube_corners(cv_image)
        if detected is None:
            self.get_logger().warn('Cube not visible -- holding position.',
                                    throttle_duration_sec=1.0)
            self._publish_qdot(np.zeros(self.n_joints), dt)
            self._show(cv_image)
            return

        area = cv2.contourArea(detected)
        Z_current = max(self.Z_d, min(0.6, 120.0 / math.sqrt(max(area, 1.0))))

        for i in range(4):
            u, v = float(detected[i][0]), float(detected[i][1])
            x = (u - self.cam.get_u0()) / self.cam.get_px()
            y = (v - self.cam.get_v0()) / self.cam.get_py()
            self.s[i].buildFrom(x, y, Z_current)
            cv2.circle(cv_image, (int(u), int(v)), 5, (0, 255, 0), -1)
            
            # Draw also the target
            u_star = self.cam.get_px() * self.s_star[i].get_x() + self.cam.get_u0() * self.s_star[i].get_y()
            v_star = self.cam.get_py() * self.s_star[i].get_y() + self.cam.get_v0() * self.s_star[i].get_Z()
            cv2.circle(cv_image, (int(u_star), int(v_star)), 5, (255, 0, 0), -1)

        v_c = self.task.computeControlLaw()  # camera-frame twist, vx..wz
        err = self.task.getError()
        norm_e = err.frobeniusNorm() if hasattr(err, 'frobeniusNorm') else float(np.linalg.norm(np.array(err)))
        v_c_np = np.array([v_c[i] for i in range(6)], dtype=float)

        J, R = self._jacobian_and_camera_rotation()
        R6 = np.block([[R, np.zeros((3, 3))], [np.zeros((3, 3)), R]])
        v_base = R6 @ v_c_np  # rotate camera-frame twist into base-frame axes

        qdot = np.zeros(self.n_joints)

        if self.state == 1:
            # Centering: solve for J1-J5 jointly, J6 locked.
            qdot[:5] = self._solve_qdot(J[:, :5], v_base)
            self.get_logger().info(f'[STATE 1] centering, |e|={norm_e:.2f}px', throttle_duration_sec=0.5)

            if norm_e < self.centering_error_threshold:
                self.get_logger().warn('Cube centered -- switching to STATE 2 (orthogonal alignment).')
                self.state = 2

        elif self.state == 2:
            q4, q5 = self.current_q[3], self.current_q[4]
            qdot4 = float(np.clip(self.phase2_gain * (self.target_j4 - q4),
                                   -self.joint_vel_limit, self.joint_vel_limit))
            qdot5 = float(np.clip(self.phase2_gain * (self.target_j5 - q5),
                                   -self.joint_vel_limit, self.joint_vel_limit))

            # Camera motion induced by the J4/J5 rotation (feedforward)
            induced_v = J[:, 3:5] @ np.array([qdot4, qdot5])

            # J1-J3 cancel the induced motion AND track residual visual error
            v_target = v_base - induced_v
            qdot[:3] = self._solve_qdot(J[:, :3], v_target)
            qdot[3] = qdot4
            qdot[4] = qdot5
            # J6 stays locked (qdot[5] = 0)

            self.get_logger().info(
                f'[STATE 2] aligning J4/J5 (q4={q4:.2f}->{self.target_j4:.2f}, '
                f'q5={q5:.2f}->{self.target_j5:.2f}) |e|={norm_e:.2f}px',
                throttle_duration_sec=0.5)

            if abs(self.target_j4 - q4) < 0.02 and abs(self.target_j5 - q5) < 0.02:
                self.get_logger().info('Orthogonal alignment reached.', throttle_duration_sec=2.0)

        self._publish_qdot(qdot, dt)
        self._show(cv_image)

    # ------------------------------------------------------------------
    def _publish_qdot(self, qdot: np.ndarray, dt: float):
        new_positions = [self.current_q[i] + float(qdot[i]) * dt for i in range(self.n_joints)]
        traj_msg = JointTrajectory()
        traj_msg.joint_names = self.joint_names
        point = JointTrajectoryPoint()
        point.positions = new_positions
        point.time_from_start.sec = 0
        point.time_from_start.nanosec = int(dt * 1e9)
        traj_msg.points = [point]
        self.traj_pub.publish(traj_msg)

    # ------------------------------------------------------------------
    def _show(self, cv_image):
        try:
            cv2.imshow('IBVS wrist camera', cv_image)
            cv2.waitKey(1)
        except Exception:
            pass


def main(args=None):
    rclpy.init(args=args)
    node = IBVSCubeNode()
    try:
        rclpy.spin(node)
    except KeyboardInterrupt:
        pass
    finally:
        node.destroy_node()
        cv2.destroyAllWindows()
        rclpy.shutdown()


if __name__ == '__main__':
    main()