<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.ros.org/schema/package_format3.xsd"?>
<package format="3">
  <name>kinova_control</name>
  <version>0.0.0</version>
  <description>Control visual IBVS con ViSP para Kinova en Python</description>
  <maintainer email="huro@todo.todo">huro</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <buildtool_depend>ament_cmake_python</buildtool_depend>

  <depend>rclpy</depend>
  <depend>sensor_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>cv_bridge</depend>

  <exec_depend>control_msgs</exec_depend>
  <exec_depend>trajectory_msgs</exec_depend>
  <exec_depend>python3-pykdl</exec_depend>
  <exec_depend>urdfdom_py</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>